/* global use, db */
// MongoDB Playground
// To disable this template go to Settings | MongoDB | Use Default Template For Playground.
// Make sure you are connected to enable completions and to be able to run a playground.
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.
// The result of the last command run in a playground is shown on the results panel.
// By default the first 20 documents will be returned with a cursor.
// Use 'console.log()' to print to the debug output.
// For more documentation on playgrounds please refer to
// https://www.mongodb.com/docs/mongodb-vscode/playgrounds/

// Select the database to use.
use('test');

const page = 1;
const limit = 2;

// --------- users --------
db.users.find();
// pagination to fetch
// db.users
//     .find()
//     .skip((page - 1) * limit) // Skip users that are before the current page
//     .limit(limit);

// --------- prospects ---------

// add multiple test data
// db.prospects.insertMany([
//     {
//         FullName: 'John Doe',
//         Phone: '1234567890',
//         Email: 'john.doe@example.com',
//         SumExpected: 50000,
//         Province: 'Ontario',
//         District: 'Toronto',
//         Address: '123 Main St, Toronto',
//         Avatar: 'avatar1.jpg',
//         Meeting: [
//             {
//                 MeetingDate: '2024-07-15T00:00:00.000Z',
//                 MeetingTitle: 'Initial Meeting',
//                 Purpose: 'Introduction',
//                 WhatTheySaid: 'Interested in our services.',
//                 FollowUp: '2024-07-20T00:00:00.000Z',
//                 Remark: 'Positive interaction.',
//             },
//         ],
//     },
//     {
//         FullName: 'Jane Smith',
//         Phone: '9876543210',
//         Email: 'jane.smith@example.com',
//         SumExpected: 75000,
//         Province: 'British Columbia',
//         District: 'Vancouver',
//         Address: '456 Oak St, Vancouver',
//         Avatar: 'avatar2.jpg',
//         Meeting: [],
//     },
//     {
//         FullName: 'Michael Johnson',
//         Phone: '5553334444',
//         Email: 'michael.j@example.com',
//         SumExpected: 100000,
//         Province: 'Alberta',
//         District: 'Calgary',
//         Address: '789 Maple Ave, Calgary',
//         Avatar: 'avatar3.jpg',
//         Meeting: [
//             {
//                 MeetingDate: '2024-07-18T00:00:00.000Z',
//                 MeetingTitle: 'Discussion Meeting',
//                 Purpose: 'Project details',
//                 WhatTheySaid: 'Interested but need more details.',
//                 FollowUp: '2024-07-25T00:00:00.000Z',
//                 Remark: 'Positive follow-up expected.',
//             },
//             {
//                 MeetingDate: '2024-07-22T00:00:00.000Z',
//                 MeetingTitle: 'Negotiation Meeting',
//                 Purpose: 'Finalize terms',
//                 WhatTheySaid: 'Interested in proceeding.',
//                 FollowUp: '2024-07-28T00:00:00.000Z',
//                 Remark: 'Close to agreement.',
//             },
//         ],
//     },
//     {
//         FullName: 'Emily Brown',
//         Phone: '7778889999',
//         Email: 'emily.brown@example.com',
//         SumExpected: 60000,
//         Province: 'Quebec',
//         District: 'Montreal',
//         Address: '321 Elm St, Montreal',
//         Avatar: 'avatar4.jpg',
//         Meeting: [
//             {
//                 MeetingDate: '2024-07-20T00:00:00.000Z',
//                 MeetingTitle: 'Exploratory Meeting',
//                 Purpose: 'Initial discussion',
//                 WhatTheySaid: 'Interested but exploring options.',
//                 FollowUp: '2024-07-27T00:00:00.000Z',
//                 Remark: 'Further follow-up needed.',
//             },
//         ],
//     },
//     {
//         FullName: 'David Lee',
//         Phone: '2221114444',
//         Email: 'david.lee@example.com',
//         SumExpected: 80000,
//         Province: 'Manitoba',
//         District: 'Winnipeg',
//         Address: '567 Pine Ave, Winnipeg',
//         Avatar: 'avatar5.jpg',
//         Meeting: [
//             {
//                 MeetingDate: '2024-07-19T00:00:00.000Z',
//                 MeetingTitle: 'Initial Discussion',
//                 Purpose: 'Introduction and needs',
//                 WhatTheySaid: 'Interested in our services.',
//                 FollowUp: '2024-07-24T00:00:00.000Z',
//                 Remark: 'Positive initial response.',
//             },
//             {
//                 MeetingDate: '2024-07-23T00:00:00.000Z',
//                 MeetingTitle: 'Follow-up Meeting',
//                 Purpose: 'Clarification',
//                 WhatTheySaid: 'Need more details before proceeding.',
//                 FollowUp: '2024-07-30T00:00:00.000Z',
//                 Remark: 'Further information provided.',
//             },
//         ],
//     },
// ]);
// db.prospects.find({ Prospectedby: ObjectId('66a23b030dc3b1d0118a8e8d') });

// db.users.insertMany([
//     {
//       "FullName": "Sita Gurung",
//       "Phone": "9852736498",
//       "Email": "sitagurung@example.com",
//       "Password": "P@ssw0rd",
//       "Province": "Province 1",
//       "District": "Ilam",
//       "InsuranceCompanyCategory": "General Insurance Companies",
//       "NameOfInsuranceCompany": "Sagarmatha Insurance Company Ltd.",
//       "AgentCode": "AGT123",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Rajesh Shrestha",
//       "Phone": "9841278365",
//       "Email": "rajesh.shrestha@example.com",
//       "Password": "SecurePass1",
//       "Province": "Bagmati Province",
//       "District": "Kathmandu",
//       "InsuranceCompanyCategory": "Health Insurance Companies",
//       "NameOfInsuranceCompany": "Nepal Mediciti Insurance Ltd.",
//       "AgentCode": "AGT456",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Priya Thapa",
//       "Phone": "9812345678",
//       "Email": "priya.thapa@example.com",
//       "Password": "P@ssword123",
//       "Province": "Province 2",
//       "District": "Janakpur",
//       "InsuranceCompanyCategory": "Life Insurance Companies",
//       "NameOfInsuranceCompany": "MetLife Nepal Insurance Ltd.",
//       "AgentCode": "",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Nabin Khadka",
//       "Phone": "9863152789",
//       "Email": "nabin.khadka@example.com",
//       "Password": "Nepal2023!",
//       "Province": "Gandaki Province",
//       "District": "Pokhara",
//       "InsuranceCompanyCategory": "General Insurance Companies",
//       "NameOfInsuranceCompany": "Neco Insurance Company Ltd.",
//       "AgentCode": "AGT789",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Anita Rai",
//       "Phone": "9840567321",
//       "Email": "anita.rai@example.com",
//       "Password": "Anita@123",
//       "Province": "Karnali Province",
//       "District": "Jumla",
//       "InsuranceCompanyCategory": "Health Insurance Companies",
//       "NameOfInsuranceCompany": "Siddhartha Insurance Ltd.",
//       "AgentCode": "",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Ramesh Singh",
//       "Phone": "9812345678",
//       "Email": "ramesh.singh@example.com",
//       "Password": "Singh@1234",
//       "Province": "Province 5",
//       "District": "Butwal",
//       "InsuranceCompanyCategory": "Life Insurance Companies",
//       "NameOfInsuranceCompany": "Prudential Life Insurance Nepal Ltd.",
//       "AgentCode": "AGT987",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Meera Lama",
//       "Phone": "9823456789",
//       "Email": "meera.lama@example.com",
//       "Password": "LamaMeera",
//       "Province": "Sudurpashchim Province",
//       "District": "Dhangadhi",
//       "InsuranceCompanyCategory": "General Insurance Companies",
//       "NameOfInsuranceCompany": "United Insurance Co. (Nepal) Ltd.",
//       "AgentCode": "AGT567",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Kiran Shahi",
//       "Phone": "9845671234",
//       "Email": "kiran.shahi@example.com",
//       "Password": "Shahi@5678",
//       "Province": "Bagmati Province",
//       "District": "Bhaktapur",
//       "InsuranceCompanyCategory": "Health Insurance Companies",
//       "NameOfInsuranceCompany": "Himalayan General Insurance Co. Ltd.",
//       "AgentCode": "",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Amit Joshi",
//       "Phone": "9856012345",
//       "Email": "amit.joshi@example.com",
//       "Password": "Joshi@098",
//       "Province": "Province 1",
//       "District": "Biratnagar",
//       "InsuranceCompanyCategory": "Life Insurance Companies",
//       "NameOfInsuranceCompany": "Nepal Life Insurance Company Ltd.",
//       "AgentCode": "AGT321",
//       "Avatar": "",
//     },
//     {
//       "FullName": "Shanti Devi",
//       "Phone": "9812345678",
//       "Email": "shanti.devi@example.com",
//       "Password": "DeviShanti",
//       "Province": "Province 2",
//       "District": "Birgunj",
//       "InsuranceCompanyCategory": "General Insurance Companies",
//       "NameOfInsuranceCompany": "Surya Life Insurance Co. Ltd.",
//       "AgentCode": "",
//       "Avatar": "",
//     }
//   ]
//   )

db.clients.insertMany([
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'John Doe',
        Phone: '1234567890',
        DateOfBirth: '1985-05-15',
        Email: 'johndoe@example.com',
        Province: 'Ontario',
        District: 'Toronto',
        Address: '123 Main St, Toronto, ON, M5A 1A1',
        Avatar: 'http://example.com/avatar/johndoe.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Jane Doe',
            NomineePhone: '0987654321',
            Relationship: 'Spouse',
            SumAssured: 100000,
            PremiumAmount: 1200,
            PolicyNo: 123456789,
            PolicyType: 1,
            IssueDate: '2023-01-01',
            EndDate: '2028-01-01',
            LastPaymentDate: '2024-01-01',
            PaymentMethod: 'Credit Card',
            LoanFacilities: false,
            PolicyIssueBranch: 'Main Branch',
            PhotoOfPolicy: 'http://example.com/policy/johndoe.jpg',
            PolicyFileReceivedBy: 'John Doe',
            PolicyFileReceivedDate: '2023-01-02',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Alice Smith',
        Phone: '2345678901',
        DateOfBirth: '1990-11-23',
        Email: 'alicesmith@example.com',
        Province: 'British Columbia',
        District: 'Vancouver',
        Address: '456 Oak St, Vancouver, BC, V6B 3K9',
        Avatar: 'http://example.com/avatar/alicesmith.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Bob Smith',
            NomineePhone: '1098765432',
            Relationship: 'Husband',
            SumAssured: 150000,
            PremiumAmount: 1500,
            PolicyNo: 234567890,
            PolicyType: 2,
            IssueDate: '2022-05-01',
            EndDate: '2027-05-01',
            LastPaymentDate: '2023-05-01',
            PaymentMethod: 'Bank Transfer',
            LoanFacilities: true,
            PolicyIssueBranch: 'West Branch',
            PhotoOfPolicy: 'http://example.com/policy/alicesmith.jpg',
            PolicyFileReceivedBy: 'Alice Smith',
            PolicyFileReceivedDate: '2022-05-02',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Michael Johnson',
        Phone: '3456789012',
        DateOfBirth: '1978-02-17',
        Email: 'michaeljohnson@example.com',
        Province: 'Quebec',
        District: 'Montreal',
        Address: '789 Pine St, Montreal, QC, H2X 1A1',
        Avatar: 'http://example.com/avatar/michaeljohnson.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Emily Johnson',
            NomineePhone: '2109876543',
            Relationship: 'Wife',
            SumAssured: 200000,
            PremiumAmount: 1800,
            PolicyNo: 345678901,
            PolicyType: 3,
            IssueDate: '2021-07-15',
            EndDate: '2026-07-15',
            LastPaymentDate: '2023-07-15',
            PaymentMethod: 'Cheque',
            LoanFacilities: false,
            PolicyIssueBranch: 'East Branch',
            PhotoOfPolicy: 'http://example.com/policy/michaeljohnson.jpg',
            PolicyFileReceivedBy: 'Michael Johnson',
            PolicyFileReceivedDate: '2021-07-16',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Olivia Williams',
        Phone: '4567890123',
        DateOfBirth: '1982-06-29',
        Email: 'oliviawilliams@example.com',
        Province: 'Alberta',
        District: 'Edmonton',
        Address: '101 Maple St, Edmonton, AB, T5J 2P9',
        Avatar: 'http://example.com/avatar/oliviawilliams.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Liam Williams',
            NomineePhone: '3210987654',
            Relationship: 'Brother',
            SumAssured: 50000,
            PremiumAmount: 800,
            PolicyNo: 456789012,
            PolicyType: 4,
            IssueDate: '2023-03-10',
            EndDate: '2028-03-10',
            LastPaymentDate: '2024-03-10',
            PaymentMethod: 'Debit Card',
            LoanFacilities: false,
            PolicyIssueBranch: 'North Branch',
            PhotoOfPolicy: 'http://example.com/policy/oliviawilliams.jpg',
            PolicyFileReceivedBy: 'Olivia Williams',
            PolicyFileReceivedDate: '2023-03-11',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Ethan Brown',
        Phone: '5678901234',
        DateOfBirth: '1995-12-04',
        Email: 'ethanbrown@example.com',
        Province: 'Saskatchewan',
        District: 'Saskatoon',
        Address: '202 Birch St, Saskatoon, SK, S7K 3S9',
        Avatar: 'http://example.com/avatar/ethanbrown.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Sophia Brown',
            NomineePhone: '4321098765',
            Relationship: 'Sister',
            SumAssured: 75000,
            PremiumAmount: 950,
            PolicyNo: 567890123,
            PolicyType: 1,
            IssueDate: '2020-11-01',
            EndDate: '2025-11-01',
            LastPaymentDate: '2023-11-01',
            PaymentMethod: 'Bank Transfer',
            LoanFacilities: true,
            PolicyIssueBranch: 'South Branch',
            PhotoOfPolicy: 'http://example.com/policy/ethanbrown.jpg',
            PolicyFileReceivedBy: 'Ethan Brown',
            PolicyFileReceivedDate: '2020-11-02',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Isabella Davis',
        Phone: '6789012345',
        DateOfBirth: '1988-09-12',
        Email: 'isabelladavis@example.com',
        Province: 'Manitoba',
        District: 'Winnipeg',
        Address: '303 Cedar St, Winnipeg, MB, R3C 4P4',
        Avatar: 'http://example.com/avatar/isabelladavis.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Jacob Davis',
            NomineePhone: '5432109876',
            Relationship: 'Father',
            SumAssured: 120000,
            PremiumAmount: 1300,
            PolicyNo: 678901234,
            PolicyType: 2,
            IssueDate: '2021-10-05',
            EndDate: '2026-10-05',
            LastPaymentDate: '2023-10-05',
            PaymentMethod: 'Credit Card',
            LoanFacilities: false,
            PolicyIssueBranch: 'Central Branch',
            PhotoOfPolicy: 'http://example.com/policy/isabelladavis.jpg',
            PolicyFileReceivedBy: 'Isabella Davis',
            PolicyFileReceivedDate: '2021-10-06',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Daniel Garcia',
        Phone: '7890123456',
        DateOfBirth: '1992-03-18',
        Email: 'danielgarcia@example.com',
        Province: 'Nova Scotia',
        District: 'Halifax',
        Address: '404 Spruce St, Halifax, NS, B3J 1A1',
        Avatar: 'http://example.com/avatar/danielgarcia.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Maria Garcia',
            NomineePhone: '6543210987',
            Relationship: 'Mother',
            SumAssured: 90000,
            PremiumAmount: 1000,
            PolicyNo: 789012345,
            PolicyType: 3,
            IssueDate: '2022-02-20',
            EndDate: '2027-02-20',
            LastPaymentDate: '2024-02-20',
            PaymentMethod: 'Credit Card',
            LoanFacilities: true,
            PolicyIssueBranch: 'South Branch',
            PhotoOfPolicy: 'http://example.com/policy/danielgarcia.jpg',
            PolicyFileReceivedBy: 'Daniel Garcia',
            PolicyFileReceivedDate: '2022-02-21',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Sophia Martinez',
        Phone: '8901234567',
        DateOfBirth: '1986-07-25',
        Email: 'sophiamartinez@example.com',
        Province: 'Prince Edward Island',
        District: 'Charlottetown',
        Address: '505 Fir St, Charlottetown, PE, C1A 7M3',
        Avatar: 'http://example.com/avatar/sophiamartinez.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Paul Martinez',
            NomineePhone: '7654321098',
            Relationship: 'Husband',
            SumAssured: 110000,
            PremiumAmount: 1400,
            PolicyNo: 890123456,
            PolicyType: 2,
            IssueDate: '2021-06-30',
            EndDate: '2026-06-30',
            LastPaymentDate: '2023-06-30',
            PaymentMethod: 'Debit Card',
            LoanFacilities: false,
            PolicyIssueBranch: 'East Branch',
            PhotoOfPolicy: 'http://example.com/policy/sophiamartinez.jpg',
            PolicyFileReceivedBy: 'Sophia Martinez',
            PolicyFileReceivedDate: '2021-07-01',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Lucas Taylor',
        Phone: '9012345678',
        DateOfBirth: '1993-04-09',
        Email: 'lucastaylor@example.com',
        Province: 'Newfoundland and Labrador',
        District: "St. John's",
        Address: "606 Willow St, St. John's, NL, A1A 1A1",
        Avatar: 'http://example.com/avatar/lucastaylor.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Ella Taylor',
            NomineePhone: '8765432109',
            Relationship: 'Sister',
            SumAssured: 65000,
            PremiumAmount: 900,
            PolicyNo: 901234567,
            PolicyType: 1,
            IssueDate: '2020-08-15',
            EndDate: '2025-08-15',
            LastPaymentDate: '2023-08-15',
            PaymentMethod: 'Bank Transfer',
            LoanFacilities: true,
            PolicyIssueBranch: 'North Branch',
            PhotoOfPolicy: 'http://example.com/policy/lucastaylor.jpg',
            PolicyFileReceivedBy: 'Lucas Taylor',
            PolicyFileReceivedDate: '2020-08-16',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Mia Anderson',
        Phone: '0123456789',
        DateOfBirth: '1989-01-30',
        Email: 'miaanderson@example.com',
        Province: 'Northwest Territories',
        District: 'Yellowknife',
        Address: '707 Elm St, Yellowknife, NT, X1A 1A1',
        Avatar: 'http://example.com/avatar/miaanderson.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Henry Anderson',
            NomineePhone: '9876543210',
            Relationship: 'Husband',
            SumAssured: 95000,
            PremiumAmount: 1100,
            PolicyNo: 123456789,
            PolicyType: 4,
            IssueDate: '2022-12-15',
            EndDate: '2027-12-15',
            LastPaymentDate: '2023-12-15',
            PaymentMethod: 'Cheque',
            LoanFacilities: false,
            PolicyIssueBranch: 'Central Branch',
            PhotoOfPolicy: 'http://example.com/policy/miaanderson.jpg',
            PolicyFileReceivedBy: 'Mia Anderson',
            PolicyFileReceivedDate: '2022-12-16',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Noah Thomas',
        Phone: '1234509876',
        DateOfBirth: '1983-11-09',
        Email: 'noahthomas@example.com',
        Province: 'Yukon',
        District: 'Whitehorse',
        Address: '808 Pinecrest St, Whitehorse, YT, Y1A 1A1',
        Avatar: 'http://example.com/avatar/noahthomas.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Grace Thomas',
            NomineePhone: '6789012345',
            Relationship: 'Daughter',
            SumAssured: 85000,
            PremiumAmount: 1050,
            PolicyNo: 234567890,
            PolicyType: 3,
            IssueDate: '2021-09-20',
            EndDate: '2026-09-20',
            LastPaymentDate: '2023-09-20',
            PaymentMethod: 'Credit Card',
            LoanFacilities: true,
            PolicyIssueBranch: 'West Branch',
            PhotoOfPolicy: 'http://example.com/policy/noahthomas.jpg',
            PolicyFileReceivedBy: 'Noah Thomas',
            PolicyFileReceivedDate: '2021-09-21',
        },
    },
    {
        OwnedBy: '66a23b030dc3b1d0118a8e8d',
        FullName: 'Ava Harris',
        Phone: '2345012345',
        DateOfBirth: '1987-08-17',
        Email: 'avaharris@example.com',
        Province: 'Nunavut',
        District: 'Iqaluit',
        Address: '909 Arctic St, Iqaluit, NU, X0A 1A1',
        Avatar: 'http://example.com/avatar/avaharris.jpg',
        ClientInsuranceInfo: {
            NameOfNominee: 'Ethan Harris',
            NomineePhone: '7890123456',
            Relationship: 'Son',
            SumAssured: 105000,
            PremiumAmount: 1200,
            PolicyNo: 345678901,
            PolicyType: 2,
            IssueDate: '2020-04-15',
            EndDate: '2025-04-15',
            LastPaymentDate: '2023-04-15',
            PaymentMethod: 'Debit Card',
            LoanFacilities: false,
            PolicyIssueBranch: 'Central Branch',
            PhotoOfPolicy: 'http://example.com/policy/avaharris.jpg',
            PolicyFileReceivedBy: 'Ava Harris',
            PolicyFileReceivedDate: '2020-04-16',
        },
    },
]);
